"""
Audit trail for the experiments.

Each run records: identifier, UTC timestamp, script and its hash, random seed,
environment versions, SHA-256 of the inputs and of every artefact produced, and
the numerical findings the experiment claims.

Produces two complementary artefacts:
  - results/RUN_MANIFEST.json : machine-readable, cumulative. Lets you verify later
    whether a result file still corresponds to the run that generated it.
  - results/AUDIT-LOG.md      : human-readable, append-only, for reporting.

To verify afterwards:  python _audit.py verify
"""

import hashlib
import json
import platform
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

RESULTS = Path("results")
MANIFEST = RESULTS / "RUN_MANIFEST.json"
LOG = RESULTS / "AUDIT-LOG.md"


def sha256(path):
    p = Path(path)
    if not p.exists():
        return None
    h = hashlib.sha256()
    with p.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def _env():
    mods = {}
    for name in ("numpy", "pandas", "scipy", "sklearn", "statsmodels", "matplotlib"):
        try:
            mods[name] = __import__(name).__version__
        except Exception:
            mods[name] = None
    return {"python": sys.version.split()[0], "platform": platform.platform(),
            "packages": mods}


class Run:
    """Context for a single experiment run."""

    def __init__(self, run_id, title, script, seed, inputs=(), notes=""):
        self.d = {
            "run_id": run_id, "title": title, "script": script,
            "script_sha256": sha256(script), "seed": seed, "notes": notes,
            "timestamp_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
            "environment": _env(),
            "inputs": {str(i): sha256(i) for i in inputs},
            "outputs": {}, "findings": {},
        }

    def output(self, path, description=""):
        self.d["outputs"][str(path)] = {"sha256": sha256(path),
                                        "bytes": Path(path).stat().st_size if Path(path).exists() else None,
                                        "description": description}
        return path

    def finding(self, key, value, note=""):
        self.d["findings"][key] = {"value": value, "note": note}

    def close(self):
        RESULTS.mkdir(exist_ok=True)
        runs = json.loads(MANIFEST.read_text()) if MANIFEST.exists() else []
        runs = [r for r in runs if r.get("run_id") != self.d["run_id"]]   # replaces re-runs
        runs.append(self.d)
        MANIFEST.write_text(json.dumps(runs, indent=2, ensure_ascii=False))

        lines = [f"\n## {self.d['run_id']} — {self.d['title']}\n",
                 f"- **Run (UTC):** {self.d['timestamp_utc']}",
                 f"- **Script:** `{self.d['script']}` · sha256 `{(self.d['script_sha256'] or '')[:16]}…`",
                 f"- **Seed:** {self.d['seed']}",
                 f"- **Environment:** Python {self.d['environment']['python']} · " +
                 " · ".join(f"{k} {v}" for k, v in self.d['environment']['packages'].items() if v)]
        if self.d["notes"]:
            lines.append(f"- **Note:** {self.d['notes']}")
        if self.d["inputs"]:
            lines.append("- **Inputs:**")
            lines += [f"  - `{k}` · sha256 `{(v or '')[:16]}…`" for k, v in self.d["inputs"].items()]
        if self.d["findings"]:
            lines.append("- **Claimed findings:**")
            for k, v in self.d["findings"].items():
                note = f" — {v['note']}" if v["note"] else ""
                lines.append(f"  - `{k}` = **{v['value']}**{note}")
        if self.d["outputs"]:
            lines.append("- **Artefacts produced:**")
            for k, v in self.d["outputs"].items():
                desc = f" — {v['description']}" if v["description"] else ""
                lines.append(f"  - `{k}` · sha256 `{(v['sha256'] or '')[:16]}…`{desc}")
        header = ("# Experiment audit trail\n\n"
                  "Append-only record generated by `_audit.py`. Each entry fixes the exact state "
                  "(script, seed, environment, hashes) under which every artefact in `results/` "
                  "was produced. To confirm that files have not changed since generation, run "
                  "`python _audit.py verify`.\n")
        prev = LOG.read_text(encoding="utf-8") if LOG.exists() else header
        # If the run was already recorded, drop its previous block.
        marker = f"\n## {self.d['run_id']} — "
        if marker in prev:
            head, _, rest = prev.partition(marker)
            _, _, after = rest.partition("\n## ")
            prev = head + ("\n## " + after if after else "")
        LOG.write_text(prev.rstrip("\n") + "\n" + "\n".join(lines) + "\n", encoding="utf-8")


def verify():
    """Re-check that every recorded artefact still matches its hash."""
    if not MANIFEST.exists():
        print("No manifest yet."); return 1
    runs = json.loads(MANIFEST.read_text())
    bad = miss = ok = 0
    for r in runs:
        print(f"\n{r['run_id']} — {r['title']}  ({r['timestamp_utc']})")
        for path, meta in r["outputs"].items():
            cur = sha256(path)
            if cur is None:
                print(f"  [MISSING ] {path}"); miss += 1
            elif cur != meta["sha256"]:
                print(f"  [ALTERED ] {path}"); bad += 1
            else:
                print(f"  [OK      ] {path}"); ok += 1
    print(f"\nSummary: {ok} intact, {bad} altered, {miss} missing.")
    return 0 if (bad == 0 and miss == 0) else 2


if __name__ == "__main__":
    sys.exit(verify() if len(sys.argv) > 1 and sys.argv[1] == "verify" else 0)
