"""Variable dictionary for the screening battery.

Maps every column in the source data file to the exact wording of the item as it was
administered. The item text is in SPANISH and is deliberately left untranslated: it is
the verbatim instrument as presented to participants, and rendering it in English would
misrepresent what was actually asked. English renderings used in the manuscript tables
are kept separately, in make_supplementary.py.

Note on the CBT-SQ: the administered form omits items 13 and 15 of the original 16-item
instrument. The analysis pipeline renames the remaining columns to the original
numbering; the keys here use the ADMINISTERED numbering, so cbt_13_0 below corresponds
to original item 14.

Note on the PHQ: the module administered was the eight-item PHQ-8. The "phq9" column
prefix is a local naming convention and does not indicate that the ninth item, which
asks directly about suicidal ideation, was collected. It was not.
"""

questionnaire = {
    "sexo": "sexo",
    "genero": "género",
    "edad": "edad",
    "repeticion": "repeticion",
    "nacionalidad": "nacionalidad",
    "tto_previo": "tto_previo",
    "tto_familiar_previo": "tto_familiar_previo",
    "sui_familia": "sui_familia",
    "suicidio_familiar": "suicidio_familiar",
    "phq9_1_0": "¿Te has sentido bajoneado/a, deprimido/a, irritable o desesperanzado/a?",
    "phq9_2_0": "¿Has sentido poco interés o placer al hacer las cosas?",
    "phq9_3_0": "¿Has sentido problemas para quedarte dormido/a, permanecer dormido/a, o has estado durmiendo demasiado?",
    "phq9_4_0": "¿Te has sentido cansado/a o con poca energía?",
    "phq9_5_0": "¿Has sentido poco apetito, has bajado de peso o has comido excesivamente?",
    "phq9_6_0": "¿Te has sentido mal respecto a ti mismo/a o has sentido que tú eres un/a fracasado/a, o que has decepcionado/a a tu familia o a ti mismo/a?",
    "phq9_7_0": "¿Has tenido problemas para concentrarte en actividades como trabajos escolares, leer o ver televisión?",
    "phq9_8_0": "¿Te has movido o hablado tan lento que las otras personas podrían haberlo notado? O al contrario ¿Has estado tan inquieto/a que estabas moviéndote de un lado para otro mucho más de lo usual?",
    "phq9_total_0": "Sumatoria de 1-9",
    "gad7_1_0": "Sentirte nervioso (a), ansiosos (a), o inquieto (a)?",
    "gad7_2_0": "No poder parar o controlar la preocupación?",
    "gad7_3_0": "Preocuparte mucho sobre diferentes cosas?",
    "gad7_4_0": "Tener problemas para relajarte?",
    "gad7_5_0": "Sentirte tan agitado que no puedes sentarte quieto (a)?",
    "gad7_6_0": "Enojarte o molestarte muy fácilmente?",
    "gad7_7_0": "Sentirte con miedo, como si algo muy malo fuera a suceder?",
    "gad7_8_0": "gad7_8_0",
    "gad7_total_0": "Suma 1-7",
    "cape-p15_1_0": "Ideación paranoide - ¿Has sentido como si la gente te lanzara indirectas o dijera cosas con doble sentido?",
    "cape-p15_1_2": "Ideación paranoide - ¿Has sentido como si algunas personas no son lo que parecen ser?",
    "cape-p15_3_0": "Ideación paranoide - ¿Has sentido como que te persiguen de alguna manera?",
    "cape-p15_4_0": "Ideación paranoide - ¿Has sentido como si hubiera una conspiración en tu contra?",
    "cape-p15_5_0": "Ideación paranoide - ¿Has sentido que la gente te mira extraño debido a tu apariencia?",
    "cape-p15_6_0": "Experiencias bizarras - ¿Has sentido que ciertos artefactos electrónicos como los computadores, pueden influir en tus pensamientos?",
    "cape-p15_7_0": "Experiencias bizarras - ¿Has sentido como si te estuvieran sacando los pensamientos de tu cabeza?",
    "cape-p15_8_0": "Experiencias bizarras - ¿Has sentido como si tus pensamientos no fueran tuyos?",
    "cape-p15_9_0": "Experiencias bizarras - ¿Has tenido pensamientos tan intensos que te preocupó que otras personas pudieran oírlos?",
    "cape-p15_10_0": "Experiencias bizarras - ¿Sientes como si tus pensamientos se repitieran en tu mente como si fueran un eco?",
    "cape-p15_11_0": "Experiencias bizarras - ¿Has sentido como si estuvieras bajo el control de alguna fuerza o poder externo a ti?",
    "cape-p15_12_0": "Experiencias bizarras - ¿Has sentido como si un doble hubiera tomado el lugar de un miembro de tu familia, amigo o conocido?",
    "cape-p15_13_0": "Anomalías perceptuales - ¿Has escuchado voces cuando estas solo?",
    "cape-p15_14_0": "Anomalías perceptuales - ¿Has escuchado voces hablando entre sí cuando estás solo?",
    "cape-p15_15_0": "Anomalías perceptuales - ¿Has vistos objetos, personas o animales que otros no pueden ver?",
    "cape-p15_pi_0": "Suma 1-5 (ideación paranoide)",
    "cape-p15_be_0": "Suma 6-12 (experiencias bizarras)",
    "cape-p15_pa_0": "Suma 13-15 (anomalías perceptuales)",
    "cape-p15_total_0": "Suma 1-15",
    "rps_1_0": "Me siento temeroso/a cuando tengo problemas importantes",
    "rps_2_0": "Cuando tomo decisiones, NO pienso en todas las alternativas u opciones",
    "rps_3_0": "Me siento inseguro/a de mí mismo/a cuando tomo decisiones importantes",
    "rps_4_0": "Cuando mi primer intento de resolver un problema no funciona, creo que si lo sigo intentando llegaré a resolverlo",
    "rps_5_0": "Creo que mis problemas pueden ser solucionados",
    "rps_6_0": "Espero a que los problemas desaparezcan solos antes de hacer algo para resolverlos",
    "rps_7_0": "Cuando mis primeros intentos de resolver un problema fracasan, me frustro mucho",
    "rps_8_0": "No soy capaz de resolver problemas difíciles, por mucho que lo intente",
    "rps_9_0": "Espero lo que más pueda antes de intentar resolver un problema",
    "rps_10_0": "Trato de evitar resolver problemas",
    "rps_11_0": "Los problemas difíciles me hacen sentir mal",
    "rps_12_0": "Cuando resuelvo problemas, intento ver los pros (ventajas) y los contras (desventajas) de cada opción",
    "rps_13_0": "Enfrento mis problemas inmediatamente",
    "rps_14_0": "Cuando resuelvo problemas, utilizo la primera idea buena que se me pasa por la cabeza",
    "rps_15_0": "Creo que puedo resolver problemas difíciles yo solo si lo intento en serio",
    "rps_16_0": "Cuando tengo un problema, obtengo la mayor cantidad de información posible",
    "rps_17_0": "Espero tanto para resolver un problema, que después ya no puedo hacer nada",
    "rps_18_0": "Me tomo más tiempo evitando mis problemas que resolviéndolos",
    "rps_19_0": "Antes de intentar resolver un problema me planteo un objetivo específico para saber donde voy",
    "rps_20_0": "Cuando tomo decisiones, NO me tomo el tiempo necesario para pensar en las ventajas y desventajas de cada posible solución",
    "rps_21_0": "Después de llevar a la práctica una solución, compruebe hasta qué punto ha mejorado el problema",
    "rps_22_0": "Intento ver mis problemas como algo interesante para resolver",
    "rps_23_0": "Cuando resuelvo problemas se me ocurren muchas soluciones",
    "rps_24_0": "Cuando tomo decisiones, sigo instintos sin pensar en lo que pueda pasar",
    "rps_25_0": "Creo que me apuro mucho cuando tomo decisiones",
    "rps_total_0": "Suma 1-25 (resolución de problemas sociales)",
    "beck_1_0": "Espero el futuro con esperanza y entusiasmo",
    "beck_2_0": "Puedo darme por vencido, renunciar, ya que no puedo hacer mejor las cosas por mí mismo",
    "beck_3_0": "Cuando las cosas van mal, me ayuda saber que no pueden permanecer así para siempre",
    "beck_4_0": "No puedo imaginar como será mi vida dentro de 10 años",
    "beck_5_0": "Tengo bastante tiempo para llevar a cabo las cosas que quisiera poder hacer",
    "beck_6_0": "En el futuro, espero conseguir lo que me pueda interesar",
    "beck_7_0": "Mi futuro me parece oscuro",
    "beck_8_0": "Espero más cosas buenas de la vida que lo que la gente suele conseguir en promedio",
    "beck_9_0": "No logro hacer que las cosas cambien, y no existen razones para creer que pueda en el futuro",
    "beck_10_0": "Mis pasadas experiencias me han preparado bien para mi futuro",
    "beck_11_0": "Todo lo que puedo ver por delante de mí es más desagradable que agradable",
    "beck_12_0": "No espero conseguir lo que realmente deseo",
    "beck_13_0": "Cuando miro hacia el futuro, espero que seré más feliz de lo que soy ahora",
    "beck_14_0": "Las cosas no marchan como yo quisiera",
    "beck_15_0": "Tengo una gran confianza en el futuro",
    "beck_16_0": "Nunca consigo lo que deseo, por lo que es absurdo desear cualquier cosa",
    "beck_17_0": "Es muy improbable que pueda lograr una satisfacción real en el futuro",
    "beck_18_0": "El futuro me parece vago e incierto",
    "beck_19_0": "Espero más bien épocas buenas que malas",
    "beck_20_0": "No merece la pena que intente conseguir algo que desee, porque probablemente no lo lograré",
    "beck_total_0": "Suma 1-20 (Desesperanza)",
    "cbt_1_0": "Planificar actividades para los fines de semana",
    "cbt_2_0": "Involucrarme en alguna actividad, en vez de tener un comportamiento dañino",
    "cbt_3_0": "Hacer a propósito cosas entretenidas que me gustan cuando estoy sintiéndome mal",
    "cbt_4_0": "Motivarme haciendo cosas",
    "cbt_5_0": "Juntarme o socializar con otras personas aun cuando no tengo ganas",
    "cbt_6_0": "Planificar mi tiempo durante la semana",
    "cbt_7_0": "Comunicar mis necesidades en forma efectiva",
    "cbt_8_0": "Identificar situaciones que hacen empeorar mis síntomas",
    "cbt_9_0": "Identificar factores de riesgo de recaídas",
    "cbt_10_0": "Me pillo a mí mismo(a) cuando saco conclusiones apresuradas",
    "cbt_11_0": "Notar cuando comienzo a sentirme más angustiado(a)",
    "cbt_12_0": "Cuestionar mis pensamientos",
    "cbt_13_0": "Me doy cuenta de mis patrones de pensamientos negativos en el momento en que los tengo",
    "cbt_14_0": "Encontrar evidencia que apoye mis pensamientos antes de creérmelos",
    "cbt_ac_0": "Suma 1-7 (activaciòn conductual)",
    "cbt_rc_0": "Suma 8-14 (reestructuraciòn cognitiva)",
    "erq_1_0": "Cuando me quiero sentir mejor (por ejemplo más alegre o divertido), pienso en algo diferentes",
    "erq_2_0": "Guardo mis sentimientos para mí mismo(a)",
    "erq_3_0": "Cuando quiero sentirme menos mal (por ejemplo, menos triste, enojado(a) o preocupado(a)), pienso en algo diferente",
    "erq_4_0": "Cuando me estoy sintiendo bien (por ejemplo, alegre o divertido) me preocupo de no mostrarlo",
    "erq_5_0": "Cuando estoy preocupado(a) por algo, trato de pensar en ello de una manera que me ayude a sentir mejor",
    "erq_6_0": "Controlo mis emociones no mostrándolas",
    "erq_7_0": "Cuando quiero sentirme mejor por algo (por ejemplo, más alegre o divertido), cambio lo que pienso sobre ello",
    "erq_8_0": "Cuando me estoy sintiendo mal (por ejemplo, triste, enojado(a) o preocupado(a)), me preocupo de no mostrarlo",
    "erq_9_0": "Controlo mis emociones sobre las cosas cambiando la forma en que pienso en ellas",
    "erq_10_0": "Cuando me quiero sentir menos mal por algo (por ejemplo, menos triste, enojado o preocupado), cambio la manera de pensar sobre ello",
    "erc_rc_0": "suma 1,3,5,7,8,10 (Reevaluación cognitiva)",
    "er_es_0": "suma 2,4,6,9 (Supresión emocional)",
    "siq_1_0": "Pensé que sería mejor si no estuviera vivo(a)",
    "siq_2_0": "Pensé en suicidarme",
    "siq_3_0": "Pensé en cómo me suicidaría",
    "siq_4_0": "Pensé en cuándo me suicidaría",
    "siq_5_0": "Pensé en la gente que muere",
    "siq_6_0": "Pensé sobre la muerte",
    "siq_7_0": "Pensé en qué escribir en una nota suicida",
    "siq_8_0": "Pensé en escribir un testamento",
    "siq_9_0": "Pensé en decirle a la gente que planeo suicidarme",
    "siq_10_0": "Pensé en cómo se sentiría la gente si me suicidara",
    "siq_11_0": "Deseé estar muerto(a)",
    "siq_12_0": "Pensé que suicidarme resolvería mis problemas",
    "siq_13_0": "Pensé que otros estarían más felices si yo estuviera muerto(a)",
    "siq_14_0": "Deseé nunca haber nacido",
    "siq_15_0": "Pensé que a nadie le importaba si yo viviera o muriera",
    "siq_total_0": "Suma 1-15 (ideación suicida)",
}